create pantech and quectel network devices with gps enable/disable hooks

diff --git a/ltib/skeleton/rootfs/etc/sysconfig/ifcfg-sim76xx0 b/ltib/skeleton/rootfs/etc/sysconfig/ifcfg-sim76xx0
--- a/ltib/skeleton/rootfs/etc/sysconfig/ifcfg-sim76xx0
+++ b/ltib/skeleton/rootfs/etc/sysconfig/ifcfg-sim76xx0
@@ -1,22 +1,36 @@
 . $syscfg/ifcfg-wwan0
 IFNAME=sim76xx0
+vzwAPN=vzwinternet
+
+selectAPN() {
+  logger -st $IFNAME -p notice "Selecting APN: $1"
+  atCmd "AT+CGDCONT=1,\"ip\",\"$1\"$2" t60
+}
 
 useAPN() {
-  atCmd "AT+CGDCONT=1,\"ip\",\"$1\";+CFUN=1;+CGATT=1" t60
+  selectAPN "$1" ';+CGATT=1'
+}
+
+vzw() {
+#For Verizon, we must reactivate main APN after activating IMS to pass data
+  atCmd 'AT+CGDCONT=8,"ip","IMS"' t10 &&
+  atCmd 'AT+CGATT=1;+CGACT=1,8;+CGACT=0,1;+CGACT=1,1' t60
 }
 
 ifPrep() {
-  atCmd AT+CGATT=0 t30 ignore
-  atCmd 'AT+DIALMODE=0;+USBNETIP=1' t10 &&
+  atCmd 'AT+CFUN=1' && sleep 20 && #ifdown/up fails without at least this delay
+  atCmd 'AT+CGATT=0;+DIALMODE=0;+USBNETIP=1' t60 &&
   local report=`atCmd 'AT+CGDCONT?' 't10 REPORT 1,\"' 2>&1` &&
-  local apn=`echo "$report"|awk -F, '{print $3}'|tr '[:upper:]' '[:lower:]'` ||
-    return
+  local apn=`echo "$report"|awk 'BEGIN{FS=",";ORS=""};\
+    {apn=$3;gsub(/^\s+|\s+$/,"",apn);print tolower(apn)}'` || return
 
   case "${apn//\"/}" in  #APN the sim76xx guessed based on SIM card
-
-    vzwinternet*)   #Must reactivate main APN after activating IMS to pass data
-      atCmd 'AT+CGDCONT=8,"ip","IMS"' t10 &&
-      atCmd 'AT+CFUN=1;+CGATT=1;+CGACT=1,8;+CGACT=0,1;+CGACT=1,1' t60
+    ${vzwAPN}*) #Must reactivate main APN after activating IMS to pass data
+      logger -st $IFNAME -p notice "APN already $vzwAPN"
+      vzw
+  ;;
+    vzw*|"")   #no APN or wrong Verizon APN selected, so select the correct one!
+      selectAPN $vzwAPN && vzw
   ;;
     broadband*)     #AT&T
       useAPN ereseller  # via US Mobile
@@ -28,8 +42,15 @@ ifPrep() {
       useAPN iot.1nce.net
   ;;
     *)
-      logger -st $IFNAME -p warn "SIM card using APN $apn"
-      atCmd 'AT+CFUN=1;+CGATT=1' t30
-
+      logger -st $IFNAME -p warning "Unrecognized APN: $apn"
+      atCmd 'AT+CGATT=1' t60
   esac
+}
+
+enableGPS() {
+#produce NEMA strings on AT/gps at 1hz
+  atCmd 'AT+CGNSSPWR=1;+CGNSSTST=1'
+}
+disableGPS() {
+  atCmd 'AT+CGNSSPWR=0'
 }
