improved error handling
in case of missing /card or invalid /card/var

diff --git a/ltib/skeleton/rootfs/etc/rc.d/init.d/sysmount b/ltib/skeleton/rootfs/etc/rc.d/init.d/sysmount
--- a/ltib/skeleton/rootfs/etc/rc.d/init.d/sysmount
+++ b/ltib/skeleton/rootfs/etc/rc.d/init.d/sysmount
@@ -1,7 +1,7 @@
 #!/bin/sh
 #mount all filesystems in /etc/fstab not marked "noauto"
 #create /var and /tmp directories and ensure that they are on
-#writable filesystems -- 3/7/25 brent@mbari.org
+#writable filesystems -- 5/19/26 brent@mbari.org
 
 prunePath() {
 #prune non-existant components from the specified filesystem path
@@ -64,11 +64,15 @@ case "$1" in
       mount -t tmpfs -o mode=1775,gid=1 RUN /run  #daemon group
       mkdir -m 1775 /run/lock && chgrp lock /run/lock
 
-      card=`realpath /card`
-      var=`realPath $card/var`
-      initial=/etc/var  #initialize /var if missing link to /run
-      [ ! -d $var/run -a -d $initial ] &&
-        redoIfRO $card "cp -af $initial $card"
+      card=`realpath /card` || {
+        echo "sysmount: Missing /card directory" >&2
+        exit 2
+      }
+      var=`realPath $card/var` && {
+        initial=/etc/var  #initialize /var if missing link to /run
+        [ ! -d $var/run -a -d $initial ] &&
+          redoIfRO $card "cp -af $initial $card"
+      }
 
       #Set up temporary directories while preserving existing symlinks
       tmp=`realPath /tmp` &&
