Added fallback /sbin/hotplug script for firmware loading
coldplug disable now disables hotplug as well

diff --git a/ltib/skeleton/rootfs/usr/sbin/coldplug b/ltib/skeleton/rootfs/usr/sbin/coldplug
--- a/ltib/skeleton/rootfs/usr/sbin/coldplug
+++ b/ltib/skeleton/rootfs/usr/sbin/coldplug
@@ -1,7 +1,7 @@
 #!/bin/sh
 self=`basename $0`
 tmpMnt=/var/lock/${self}_root.$$
-devOrig=/.dev-minimal  #where to keep the original, minimal /dev
+devMin=sys/.dev-minimal  #where to keep the original, minimal /dev
 rcDir=/etc/rc.d/rc3.d
 inittab=/etc/inittab
 
@@ -28,7 +28,7 @@ mntPt() {
 }
 
 updateInittab() {
-  sed -i $@ $inittab 
+  sed -i $@ $inittab
 }
 
 updateRC() {
@@ -38,20 +38,28 @@ updateRC() {
 
 case "$1" in
  early|--early)
-  [ -d $devOrig ] || {
-    echo "Cannot restore early $self configuration due to missing $devOrig" >&2
+  mountRoot
+  [ -d $tmpMnt/$devMin ] || {
+    echo "Cannot restore early $self configuration due to missing /$devMin" >&2
     exit 2
   }
-  mountRoot
   rm -rf $tmpMnt/dev/*
-  cp -a $devOrig/* $tmpMnt/dev   &&    #revert to minimal /dev
+  cp -a $tmpMnt/$devMin/* $tmpMnt/dev   &&   #revert to minimal /dev
   updateInittab 's/^DEV.:/#&/g' &&    #disable starting udev from inittab
   updateRC 'disable/*coldplug'
 ;;
  late|--late)
   mountRoot
-  rm -rf $tmpMnt/dev/*
-  cp -a /dev/* $tmpMnt/dev &&   #store /dev for currently configured hardware
+  if [ -e $tmpMnt/$devMin ]; then
+    [ -d $tmpMnt/$devMin ] || {
+      echo "/$devMin should be a directory!" >&2
+      exit 7
+    }
+    rm -rf $tmpMnt/dev/*
+  else
+    mkdir $tmpMnt/$devMin && mv $tmpMnt/dev/* $tmpMnt/$devMin
+  fi || exit
+  cp -a /dev/* $tmpMnt/dev && #update for currently configured hardware
   updateInittab 's/^#\(DEV.:\)/\1/g' $inittab && #start udev from inittab
   updateRC '*coldplug' disable
 ;;
@@ -60,11 +68,11 @@ case "$1" in
   updateRC '*coldplug' disable
 ;;
  *) cat >&2 <<END
-Configure recognition of installed devices -- 11/22/19 brent@mbari.org
+Configure recognition of installed devices -- 11/23/19 brent@mbari.org
  Usage:
   $self early   #delay boot up until all installed devices recognized
-  $self late    #recognize installed devices only after boot up completed
-  $self disable #do not recognize (USB) devices until they are plugged in
+  $self late    #recognize new devices only after boot up completed
+  $self disable #never recognize newly installed devices
  Notes:
   early is the default -- most flexible, but slow.
   $self late typically boots up about 20 seconds faster than $self early.
