Output error message as well as returning exit code on error

diff --git a/ltib/skeleton/rootfs/usr/sbin/dhcp b/ltib/skeleton/rootfs/usr/sbin/dhcp
--- a/ltib/skeleton/rootfs/usr/sbin/dhcp
+++ b/ltib/skeleton/rootfs/usr/sbin/dhcp
@@ -37,5 +37,8 @@ case "$act" in
   stop) signalDHCPclient HUP
 ;;
   *) usage
-esac
-
+esac || {
+  err=$?
+  echo "DHCP $act for ${IFALIAS:-$IFNAME} failed!" 2>&1
+  exit $err
+}
