vpnUp explicitly verifies vpn interface is already up
reconnectVPN relies on ppp links bringing up VPN in their ip-up script
retry ESPshore VPN indefinately

diff --git a/ltib/skeleton/rootfs/usr/sbin/reconnectVPN b/ltib/skeleton/rootfs/usr/sbin/reconnectVPN
--- a/ltib/skeleton/rootfs/usr/sbin/reconnectVPN
+++ b/ltib/skeleton/rootfs/usr/sbin/reconnectVPN
@@ -1,17 +1,16 @@
 #!/bin/sh
 cell=ppp8   #cellular radio modem
-#vpn=ppp6
+vpn=ppp6
 
-[ "$vpn" ] && ifdown $vpn
-[ "$cell" ] && {
-  #don't attempt to restore cell interface if modem failed < 15 minutes ago
+if [ "$cell" ]; then
+  #don't attempt to restore cell interface if modem failed < 5 minutes ago
   lastReset=`head -n1 /var/run/I2Cgate.reset 2>/dev/null`
   [ "$lastReset" ] && sinceReset=$(($(date +%s)-$lastReset))
-  if [ $? != 0 -o "$sinceReset" -ge 900 -o "$sinceReset" -lt 0 ]; then
+  if [ $? != 0 -o "$sinceReset" -ge 300 -o "$sinceReset" -lt 0 ]; then
     ifdown $cell
-    ifup $cell
-    sleep 30
+    ifup $cell  #assumes $cell brings up vpn
   fi
-}
-[ "$vpn" ] || exit 0
-ifup $vpn
+elif [ "$vpn" ]; then
+  ifdown $vpn
+  ifup $vpn
+fi
