More testing on dynamic networking configuration scripts

diff --git a/ltib/skeleton/rootfs/usr/sbin/tunnel2shore b/ltib/skeleton/rootfs/usr/sbin/tunnel2shore
--- a/ltib/skeleton/rootfs/usr/sbin/tunnel2shore
+++ b/ltib/skeleton/rootfs/usr/sbin/tunnel2shore
@@ -10,10 +10,10 @@ self=`basename $0`
 : ${shoreUser:=`hostname`}
 : ${shoreSSH:="-p2323 $shoreUser@$shore"}
 [ "$1" ] && { cat >&2 <<END
-Bring up ssh tunnel to $shore for ssh and smtp -- 11/11/19 brent@mbari.org
+Bring up ssh tunnel to $shore for ssh and smtp -- 11/13/19 brent@mbari.org
 Retries every $noGateDelay seconds until internet is available
 END
-  exit 2
+  exit 9
 }
 tunHosts=/var/run/$self.hosts
 export HOME
@@ -24,19 +24,30 @@ export HOME
   set -x
 }
 
-trap "rm -f $tunHosts $pidFn" EXIT
-trap "pkill -P $$; exit 1" TERM HUP INT QUIT
-trap "" USR1 USR2
+#restart if network changed  (pid does not change!)
+trap "pkill -P $$; wait; rm -f $tunHosts; exec $0" HUP
+#Empty .pid file to delay restart after waiting until tunnel is closed.
+trap "pkill -P $$; rm -f $tunHosts; wait; >$pidFn; exec $0" USR1
+#clean up on request to exit
+trap "pkill -P $$; wait; rm -f $tunHosts $pidFn; exit 129" TERM INT QUIT
 
 if [ -s "$pidFn" ];then
-  #kill any other instances
-  oldPID=`cat $pidFn 2>/dev/null` &&
-    kill -0 "$oldPID" 2>/dev/null && kill -HUP $oldPID
-  fuser -sk 25/tcp
-  echo $$ >$pidFn
+  #terminate any other instances
+  oldPID=`cat $pidFn 2>/dev/null` && [ "$oldPID" != $$ ] && {
+    kill "$oldPID" 2>/dev/null && {
+      secs=20
+      while let secs--; do
+        sleep 1
+        kill -0 $oldPID || break
+      done
+    }
+    echo $$ >$pidFn
+  }
+  fuser -sk 25/tcp  #in case previous tunnel did not close
 elif [ -e "$pidFn" ]; then  #empty .pid file
   echo $$ >$pidFn
-  echo "Delaying reopening $shore tunnel for $noGateDelay seconds"
+#  sleep 20
+#  echo "Reopening $shore tunnel in $noGateDelay seconds"
   sleep $noGateDelay
 else  #missing .pid file
   echo $$ >$pidFn
@@ -49,8 +60,9 @@ topIf() {
   echo ${iface###}
 }
 
-while [ ! `topIf` ]; do
-  echo "No Network Gateway -- reopening $shore tunnel in $noGateDelay seconds"
+sleep 5  #wait for net config to stabilize
+while [ ! "$(topIf)" ]; do
+#  echo "No Network Gateway -- reopening $shore tunnel in $noGateDelay seconds"
   sleep $noGateDelay
 done
 
@@ -61,9 +73,6 @@ cat $tunHosts >>/etc/hosts
 tunnels="-L25:$shore:25 -L873:$shore:873"
 tunArgs="-oExitOnForwardFailure=yes -ygNK 180 $shoreSSH"
 local=localhost:22
-
-#delay until tunnel is closed.  Empty .pid file on exit to delay its reopening.
-trap "trap '' USR1 EXIT; pkill -P $$; wait; >$pidFn; exit 1" USR1
 
 #first, try the port previously assigned us
 echo "Opening tunnel to $shore"
