enforce minimum time between modem resets

diff --git a/esp/scripts/rootfs/etc/ppp/gprs-connect b/esp/scripts/rootfs/etc/ppp/gprs-connect
--- a/esp/scripts/rootfs/etc/ppp/gprs-connect
+++ b/esp/scripts/rootfs/etc/ppp/gprs-connect
@@ -10,11 +10,12 @@ tracefn=/tmp/${tag}.trace
 }
 
 export APN=$1
-resetDelay=${2--900}   #retry detach every 15 minutes
-offSecs=${3-5}
+resetHoldOff=${2--900}   #retry detach every 15 minutes
+offSecs=${3-9}           #default to 9 seconds w/pwr off
 gateway=${4-/dev/I2Cgate}
 esp=esp  #esp user for case where no espclient available
 mRstCmd="/sbin/crash/resetModem --device=$gateway $offSecs"
+lastResetFn=/var/run/`basename $gateway`.reset
 
 [ "$APN" ] || {
 cat << EOS
@@ -36,38 +37,48 @@ exit 1
 cd `dirname $0` || exit 2
 
 until /usr/sbin/chat -vf gprs-detach.chat; do
-  fuser -u $gateway 2>&1 | tr \(\) " " | (
-    while read dev espPid espUser ignored; do
-      if [ -n "$espPid" -a -n "$espUser" ]; then
-        logger -t$tag \
-          "Modem won't detach -- cycling power via $espUser's espclient"
-        result=$(exec 5>&1; su - $espUser >&2 <<EOS
-          espclient --server=$espPid $tag >&5 <<EOC
-            Sleepy.cycleModemPower! $offSecs
+  resetDelay=$resetHoldOff
+  [ $resetDelay -lt 0 ] && resetDelay=$((-($resetDelay)))
+  now=`date +%s`
+  lastReset=`cat $lastResetFn 2>/dev/null` &&
+  secsSinceReset=$(($now-$lastReset))
+  if [ $? != 0 -o "$secsSinceReset" -ge $resetDelay ]; then
+    echo $now >$lastResetFn
+    fuser -u $gateway 2>&1 | tr \(\) " " | (
+      while read dev espPid espUser ignored; do
+        if [ -n "$espPid" -a -n "$espUser" ]; then
+          logger -t$tag \
+            "Modem won't detach -- cycling power via $espUser's espclient"
+          result=$(exec 5>&1; su - $espUser >&2 <<EOS
+            espclient --server=$espPid $tag >&5 <<EOC
+              Sleepy.cycleModemPower! $offSecs
 EOC
 EOS
-        ) && {
-          set -- $result
-          [ -z "$3" -a "$1" = "=>" -a "$2" -eq "$offSecs" ] && return
-        }
-      fi
-    done
-    # reset modem directly first as user esp
-    #   failing that, output warning in log and try resetting as root
-    logger -t$tag "Modem won't detach, no espclient -- resetting via $gateway"
-    errmsg=`su $esp -c "$mRstCmd" 2>&1 >&-` && return
-    logger -t$tag "retrying as root after $esp failed with $errmsg"
-    errmsg=`$mRstCmd 2>&1 >&-` && return
-    logger -t$tag "also failed as root -- $errmsg"
-  )
-  [ "$resetDelay" -ge 0 ] && {
-    [ $resetDelay -ne 0 ] && {
+          ) && {
+            set -- $result
+            [ -z "$3" -a "$1" = "=>" -a "$2" -eq "$offSecs" ] && return
+          }
+        fi
+      done
+      # reset modem directly first as user esp
+      #   failing that, output warning in log and try resetting as root
+      logger -t$tag "Modem won't detach, no espclient -- resetting via $gateway"
+      errmsg=`su $esp -c "$mRstCmd" 2>&1 >&-` && return
+      logger -t$tag "retrying as root after $esp failed with $errmsg"
+      errmsg=`$mRstCmd 2>&1 >&-` && return
+      logger -t$tag "also failed as root -- $errmsg"
+    )
+  else
+    resetDelay=$(($resetDelay - $secsSinceReset))
+  fi
+  [ $resetHoldOff -ge 0 ] && {
+    [ $resetHoldOff -ne 0 ] && {
       logger -t$tag "Waiting $resetDelay seconds before reporting failure"
       sleep $resetDelay
     }
     exit 7
   }
-  logger -t$tag "Waiting $((-($resetDelay))) seconds before retrying..."
-  sleep $((-($resetDelay)))
+  logger -t$tag "Waiting $resetDelay seconds before retrying..."
+  sleep $resetDelay
 done
 exec /usr/sbin/chat -vEf gprs-attach.chat
